version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: womensafety-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Rija@123
      MYSQL_DATABASE: womensafety
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - womensafety-net

  app:
    build: .
    container_name: womensafety-app
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/womensafety
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Rija@123
    networks:
      - womensafety-net

volumes:
  mysql_data:

networks:
  womensafety-net:
    driver: bridge
